<?php declare(strict_types=1);

namespace Contena\Tests\Integration\Frontend\Framework\Seo;

use Doctrine\DBAL\ArrayParameterType;
use Doctrine\DBAL\Connection;
use PHPUnit\Framework\TestCase;
use Contena\Core\Content\Category\CategoryCollection;
use Contena\Core\Defaults;
use Contena\Core\Framework\Api\Util\AccessKeyHelper;
use Contena\Core\Framework\Context;
use Contena\Core\Framework\DataAbstractionLayer\Doctrine\FetchModeHelper;
use Contena\Core\Framework\DataAbstractionLayer\EntityRepository;
use Contena\Core\Framework\Test\TestCaseBase\IntegrationTestBehaviour;
use Contena\Core\Framework\Test\TestCaseBase\QueueTestBehaviour;
use Contena\Core\Framework\Uuid\Uuid;
use Contena\Core\System\Channel\ChannelCollection;
use Contena\Core\Test\Stub\Framework\IdsCollection;
use Contena\Core\Test\TestDefaults;
use Contena\Frontend\Framework\Seo\SeoUrlRoute\NavigationPageSeoUrlRoute;

/**
 * @internal
 */
class NavigationPageSeoUrlTest extends TestCase
{
    use IntegrationTestBehaviour;
    use QueueTestBehaviour;

    /**
     * @var EntityRepository<ChannelCollection>
     */
    private EntityRepository $channelRepository;

    /**
     * @var EntityRepository<CategoryCollection>
     */
    private EntityRepository $categoryRepository;

    private Connection $connection;

    protected function setUp(): void
    {
        $this->connection = static::getContainer()->get(Connection::class);
        $this->categoryRepository = static::getContainer()->get('category.repository');
        $this->channelRepository = static::getContainer()->get('channel.repository');
    }

    public function testGenerateForNewCategories(): void
    {
        $ids = new IdsCollection();

        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root'],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());

        $urls = $this->getSeoUrls($ids->getList(['root']), null);
        static::assertEmpty($urls);

        $this->createChannel($ids->create('channel'), $ids->get('root'));

        $categories = [
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root')],
            ['id' => $ids->create('b'), 'name' => 'b', 'parentId' => $ids->get('a')],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());

        $urls = $this->getSeoUrls($ids->getList(['a', 'b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);
    }

    public function testSwitchNavigationId(): void
    {
        $ids = new IdsCollection();

        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root', 'active' => true],
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root'), 'active' => true],
            ['id' => $ids->create('b'), 'name' => 'b', 'parentId' => $ids->get('a'), 'active' => true],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());

        $this->createChannel($ids->create('channel'), $ids->get('root'));

        // Channel navigation id switch detected, SEO URLs are generated by message queue.
        $this->runWorker();

        $urls = $this->getSeoUrls($ids->getList(['root', 'a', 'b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        $this->channelRepository->update([
            ['id' => $ids->get('channel'), 'navigationCategoryId' => $ids->get('a')],
        ], Context::createDefaultContext());

        $this->runWorker();

        $urls = $this->getSeoUrls($ids->getList(['root', 'a', 'b']), $ids->get('channel'));

        static::assertCount(3, $urls);
        // old urls are still exists
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        // new url generated
        static::assertArrayHasKey('b/', $urls);
    }

    public function testSwitchParentId(): void
    {
        $ids = new IdsCollection();

        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root', 'active' => true],
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root'), 'active' => true],
            ['id' => $ids->create('b'), 'name' => 'b', 'parentId' => $ids->get('a'), 'active' => true],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());

        $this->createChannel($ids->create('channel'), $ids->get('root'));

        // Channel navigation id switch detected, SEO URLs are generated by message queue.
        $this->runWorker();

        $urls = $this->getSeoUrls($ids->getList(['root', 'a', 'b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        $this->categoryRepository->update([
            ['id' => $ids->get('b'), 'parentId' => $ids->get('root')],
        ], Context::createDefaultContext());

        $urls = $this->getSeoUrls($ids->getList(['root', 'a', 'b']), $ids->get('channel'));

        static::assertCount(3, $urls);
        // old urls are still exists
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        // new url generated
        static::assertArrayHasKey('b/', $urls);
    }

    public function testUpdateName(): void
    {
        $ids = new IdsCollection();

        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root', 'active' => true],
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root'), 'active' => true],
            ['id' => $ids->create('b'), 'name' => 'b', 'parentId' => $ids->get('a'), 'active' => true],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());
        $this->createChannel($ids->create('channel'), $ids->get('root'));

        $this->runWorker();

        $urls = $this->getSeoUrls($ids->getList(['a', 'b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        // old urls are still exists
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        $this->categoryRepository->update(
            [
                ['id' => $ids->get('b'), 'name' => 'x'],
            ],
            Context::createDefaultContext()
        );

        $urls = $this->getSeoUrls($ids->getList(['b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        // old urls are still exists
        static::assertArrayHasKey('a/b/', $urls);

        // new url is generated
        static::assertArrayHasKey('a/x/', $urls);
    }

    public function testFooterMenu(): void
    {
        $ids = new IdsCollection();

        /**
         * navigation
         *    └── a
         *        └── b
         * footer
         *       service
         *          ├── newsletter
         *          └── partner
         *       information
         *          ├── imprint
         *          └── terms
         */
        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root'],
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root')],
            ['id' => $ids->create('b'), 'name' => 'b', 'parentId' => $ids->get('a')],

            ['id' => $ids->create('footer'), 'name' => 'Footer'],

            ['id' => $ids->create('info'), 'name' => 'Information', 'parentId' => $ids->get('footer')],
            ['id' => $ids->create('terms'), 'name' => 'General terms and conditions', 'parentId' => $ids->get('info')],
            ['id' => $ids->create('imprint'), 'name' => 'Imprint', 'parentId' => $ids->get('info')],

            ['id' => $ids->create('service'), 'name' => 'Service', 'parentId' => $ids->get('footer')],
            ['id' => $ids->create('newsletter'), 'name' => 'Newsletter', 'parentId' => $ids->get('service')],
            ['id' => $ids->create('partner'), 'name' => 'Partner', 'parentId' => $ids->get('service')],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());

        $this->createChannel(
            $ids->create('channel'),
            $ids->get('root'),
            $ids->get('footer'),
            $ids->get('service')
        );

        $this->runWorker();

        $urls = $this->getSeoUrls($ids->all(), $ids->get('channel'));

        static::assertCount(8, $urls);

        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        static::assertArrayHasKey('Information/', $urls);
        static::assertArrayHasKey('Information/General-terms-and-conditions/', $urls);
        static::assertArrayHasKey('Information/Imprint/', $urls);

        static::assertArrayHasKey('Service/', $urls);
        static::assertArrayHasKey('Service/Newsletter/', $urls);
        static::assertArrayHasKey('Service/Partner/', $urls);
    }

    public function testServiceMenuNotInFooter(): void
    {
        $ids = new IdsCollection();

        /**
         * navigation
         *    └── a
         *        └── b
         * service
         *      ├── newsletter
         *      └── partner
         * footer
         *       information
         *          ├── imprint
         *          └── terms
         */
        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root'],
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root')],
            ['id' => $ids->create('b'), 'name' => 'b', 'parentId' => $ids->get('a')],

            ['id' => $ids->create('footer'), 'name' => 'Footer'],

            ['id' => $ids->create('info'), 'name' => 'Information', 'parentId' => $ids->get('footer')],
            ['id' => $ids->create('terms'), 'name' => 'General terms and conditions', 'parentId' => $ids->get('info')],
            ['id' => $ids->create('imprint'), 'name' => 'Imprint', 'parentId' => $ids->get('info')],

            ['id' => $ids->create('service'), 'name' => 'Service'],
            ['id' => $ids->create('newsletter'), 'name' => 'Newsletter', 'parentId' => $ids->get('service')],
            ['id' => $ids->create('partner'), 'name' => 'Partner', 'parentId' => $ids->get('service')],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());

        $this->createChannel(
            $ids->create('channel'),
            $ids->get('root'),
            $ids->get('footer'),
            $ids->get('service')
        );

        $this->runWorker();

        $urls = $this->getSeoUrls($ids->all(), $ids->get('channel'));

        static::assertCount(7, $urls);

        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/b/', $urls);

        static::assertArrayHasKey('Information/', $urls);
        static::assertArrayHasKey('Information/General-terms-and-conditions/', $urls);
        static::assertArrayHasKey('Information/Imprint/', $urls);

        static::assertArrayHasKey('Newsletter/', $urls);
        static::assertArrayHasKey('Partner/', $urls);
    }

    public function testDuplicateUrl(): void
    {
        $ids = new IdsCollection();

        $categories = [
            ['id' => $ids->create('root'), 'name' => 'root', 'active' => true],
            ['id' => $ids->create('a'), 'name' => 'a', 'parentId' => $ids->get('root'), 'active' => true],
            ['id' => $ids->create('b'), 'name' => 'a', 'parentId' => $ids->get('a'), 'active' => true],
        ];

        $this->categoryRepository->create($categories, Context::createDefaultContext());
        $this->createChannel($ids->create('channel'), $ids->get('root'));

        $this->runWorker();

        $urls = $this->getSeoUrls($ids->getList(['a', 'b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        // old urls are still exists
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/a/', $urls);

        $this->categoryRepository->update([
            ['id' => $ids->get('b'), 'parentId' => $ids->get('root')],
        ], Context::createDefaultContext());

        $urls = $this->getSeoUrls($ids->getList(['a', 'b']), $ids->get('channel'));

        static::assertCount(2, $urls);
        static::assertArrayHasKey('a/', $urls);
        static::assertArrayHasKey('a/a/', $urls);

        // new url of a/ points to the category b
        static::assertSame($urls['a/'], $urls['a/a/']);
    }

    private function createChannel(
        string $id,
        string $navigationId,
        ?string $footerId = null,
        ?string $serviceId = null
    ): void {
        $countryId = $this->getValidCountryId();
        $data = [
            'id' => $id,
            'name' => 'test',
            'typeId' => Defaults::CHANNEL_TYPE_WEB,
            'accessKey' => AccessKeyHelper::generateAccessKey('channel'),
            'languageId' => Defaults::LANGUAGE_SYSTEM,
            'countryId' => $countryId,
            'navigationCategoryId' => $navigationId,
            'navigationCategoryVersionId' => Defaults::LIVE_VERSION,
            'languages' => [['id' => Defaults::LANGUAGE_SYSTEM]],
            'countries' => [['id' => $countryId]],
            'memberGroupId' => TestDefaults::FALLBACK_MEMBER_GROUP,
            'domains' => [
                [
                    'languageId' => Defaults::LANGUAGE_SYSTEM,
                    'snippetSetId' => $this->getSnippetSetIdForLocale('en-GB'),
                    'url' => 'http://test.de',
                ],
            ],
        ];

        if ($footerId !== null) {
            $data['footerCategoryId'] = $footerId;
            $data['footerCategoryVersionId'] = Defaults::LIVE_VERSION;
        }

        if ($serviceId !== null) {
            $data['serviceCategoryId'] = $serviceId;
            $data['serviceCategoryVersionId'] = Defaults::LIVE_VERSION;
        }

        $this->channelRepository->create([$data], Context::createDefaultContext());
    }

    /**
     * @param array<string, string> $ids
     *
     * @return mixed[]
     */
    private function getSeoUrls(array $ids, ?string $channelId): array
    {
        $query = $this->connection->createQueryBuilder();
        $query->addSelect(
            'seo_path_info',
            'path_info',
        );
        $query->from('seo_url');
        $query->andWhere('foreign_key IN (:ids)');
        $query->andWhere('route_name = :routeName');
        $query->andWhere('language_id = :language');
        if ($channelId) {
            $query->andWhere('channel_id = :channel');
            $query->setParameter('channel', Uuid::fromHexToBytes($channelId));
        }

        $query->setParameter('ids', Uuid::fromHexToBytesList(array_values($ids)), ArrayParameterType::BINARY);
        $query->setParameter('routeName', NavigationPageSeoUrlRoute::ROUTE_NAME);
        $query->setParameter('language', Uuid::fromHexToBytes(Defaults::LANGUAGE_SYSTEM));

        $urls = $query->executeQuery()->fetchAllAssociative();

        return FetchModeHelper::keyPair($urls);
    }
}
