Contena.Service('privileges').addPrivilegeMappingEntry({
    category: 'permissions',
    parent: 'content',
    key: 'blog',
    roles: {
        viewer: {
            privileges: [
                'blog:read',
                'blog_translation:read',
                'blog_media:read',
                'blog_visibility:read',
                'blog_main_category:read',
                'blog_category:read',
                'blog_tag:read',
                'category:read',
                'channel:read',
                'media:read',
                'tag:read',
                'seo_url:read',
                'content_layout:read',
                'blog_content_layout:read',
                'custom_field_set:read',
                'custom_field:read',
                'custom_field_set_relation:read',
            ],
            dependencies: [],
        },
        editor: {
            privileges: [
                'blog:update',
                'blog_translation:create',
                'blog_translation:update',
                'blog_media:create',
                'blog_media:update',
                'blog_media:delete',
                'blog_visibility:create',
                'blog_visibility:update',
                'blog_visibility:delete',
                'blog_main_category:create',
                'blog_main_category:update',
                'blog_main_category:delete',
                'blog_category:create',
                'blog_category:delete',
                'blog_tag:create',
                'blog_tag:delete',
                'tag:create',
                'seo_url:create',
                'seo_url:update',
                'seo_url:delete',
                Contena.Service('privileges').getPrivileges('media.creator'),
            ],
            dependencies: ['blog.viewer'],
        },
        creator: {
            privileges: ['blog:create'],
            dependencies: [
                'blog.viewer',
                'blog.editor',
            ],
        },
        deleter: {
            privileges: ['blog:delete'],
            dependencies: ['blog.viewer'],
        },
    },
});
