// eslint-disable-next-line ct-deprecation-rules/private-feature-declarations
export default {
    id: 'ct-platform',
    moduleType: 'core',
    label: 'Contena Platform',
    color: '#189eff',
    icon: 'regular-cog',
    position: 20,
    level: 1,
    children: [
        {
            id: 'ct-media',
            moduleType: 'core',
            label: 'ct-media.general.mainMenuItemList',
            path: 'ct.media.index',
            parent: 'ct-platform',
            position: 10,
            children: [],
            level: 2,
        },
        {
            id: 'ct-users',
            moduleType: 'core',
            label: 'ct-users.general.mainMenuItemGeneral',
            path: 'ct.users.index',
            parent: 'ct-platform',
            position: 20,
            children: [],
            level: 2,
        },
        {
            id: 'ct-extension',
            moduleType: 'core',
            label: 'ct-extension.general.mainMenuItemGeneral',
            path: 'ct.extension.my-extensions',
            parent: 'ct-platform',
            position: 30,
            children: [],
            level: 2,
        },
        {
            id: 'ct-foo',
            moduleType: 'plugin',
            label: 'ct-foo.general.mainMenuItemList',
            path: 'ct.foo.index',
            parent: 'ct-platform',
            position: 1010,
            children: [],
            level: 2,
        },
        {
            id: 'ct-bar',
            moduleType: 'plugin',
            label: 'ct-bar.general.mainMenuItemList',
            path: 'ct.bar.index',
            parent: 'ct-platform',
            position: 1020,
            children: [],
            level: 2,
        },
    ],
};
