Contena.Service('privileges').addPrivilegeMappingEntry({
    category: 'permissions',
    parent: null,
    key: 'channel',
    roles: {
        viewer: {
            privileges: [
                'channel:read',
                'channel_type:read',
                'channel_domain:read',
                'channel_country:read',
                'channel_language:read',
                'country:read',
                'language:read',
                'snippet_set:read',
                'member_group:read',
                'category:read',
                'theme:read',
                'theme_channel:read',
                'header_content_layout:read',
                'footer_content_layout:read',
                'content_layout:read',
                'system_config:read',
            ],
            dependencies: [],
        },
        editor: {
            privileges: [
                'channel:update',
                'channel_country:create',
                'channel_country:delete',
                'channel_country:update',
                'channel_domain:create',
                'channel_domain:delete',
                'channel_domain:update',
                'channel_language:create',
                'channel_language:delete',
                'channel_language:update',
                'theme_channel:create',
                'theme_channel:delete',
                'header_content_layout:create',
                'header_content_layout:update',
                'header_content_layout:delete',
                'footer_content_layout:create',
                'footer_content_layout:update',
                'footer_content_layout:delete',
                'system_config:create',
                'system_config:update',
                'system_config:delete',
            ],
            dependencies: ['channel.viewer'],
        },
        creator: {
            privileges: ['channel:create'],
            dependencies: [
                'channel.viewer',
                'channel.editor',
            ],
        },
        deleter: {
            privileges: ['channel:delete'],
            dependencies: ['channel.viewer'],
        },
    },
});
